### ISSUE TITLE
Batch Baker + override settings

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#101]
I have many many scenes to rebake
The settings of one scene is what I'd like to use for all the other
If I use batch baker then I need to open every scene then restore settings to default, which defeats some of the benefit of batch baking
So it would be nice to have an option:
[X] override settings with 
...............                    (o)  scene settings: [SCENE]
...............                    (  )  default

**Comment by guycalledfrank** [comment]
Batch baker is provided as a separate free script that also serves as an API usage example.
You can easily extend the script with your functionality:
- Add "override settings field"
- Load the scene with the settings
- Find settings from the scene: var storage = ftRenderLightmap.FindRenderSettingsStorage();
- Copy scene settings to global (default) settings: ftLightmapStorage.CopySettings(storage, ftLightmaps.GetGlobalStorage())
- Load another scene
- Now find its own settings: storage = ftRenderLightmap.FindRenderSettingsStorage();
- Copy settings from global to scene: ftLightmapStorage.CopySettings(ftLightmaps.GetGlobalStorage(), storage)
- Bake
- etc

Updated API docs just now: https://geom.io/bakery/wiki/index.php?title=Manual#Additional_functions
