### ISSUE TITLE
this SG shader confuses the light baker

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#103]
![image](https://user-images.githubusercontent.com/26075468/120146039-55e28e00-c199-11eb-8c38-89d89e498ef8.png)
it won't light up like this (it's a simulation of the efffect using urp/lit)
![image](https://user-images.githubusercontent.com/26075468/120146100-6a268b00-c199-11eb-8e21-edb93debd02a.png)
instead it'll show up as that with that bit of texture at the bottom of the frame
![image](https://user-images.githubusercontent.com/26075468/120146222-99d59300-c199-11eb-9610-6fec6be5aa42.png)
that green yellow thing

**Comment by laurentopia** [comment]
and the rest of the lava object being black

**Comment by guycalledfrank** [comment]
What is texel density on the lava? Given it looks like solid color, I assume it's just very low?

**Comment by laurentopia** [comment]
how do i see that?

**Comment by guycalledfrank** [comment]
Using Checker Preview? 
https://geom.io/bakery/wiki/index.php?title=Manual#Checker_preview

**Comment by guycalledfrank** [comment]
General advice:
- Try using OpenImageDenoise.
- Try using solid emissive color for lava. You can hide it but put BakeryAlwaysRender component on it, so it participates in baking. Renderable lava can have a texture but not be marked as Contribute GI.

**Comment by laurentopia** [comment]
it works, thanks.
