### ISSUE TITLE
when brightness of emissive object is too high you get tons of artifacts

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#104]
like these blue blotches
![image](https://user-images.githubusercontent.com/26075468/120146319-c093c980-c199-11eb-8bda-512965e45145.png)

all using URP/lit material

**Comment by laurentopia** [comment]
i thought the imprecision glitches were resolved, could it be resolved only for lights and not for emissive objects?0

![image](https://user-images.githubusercontent.com/26075468/120146398-def9c500-c199-11eb-8b15-4793c3dcda11.png)

**Comment by guycalledfrank** [comment]
Possibly related to denoiser (?). Can you try it with OpenImageDenoise?
Also I guess the irregular / high contrast texture of lava just doesn't play well with ray-tracing, as rays can miss the bright parts of the texture easily, leading to (incorrectly denoised?) firefles (just like this: https://geom.io/bakery/wiki/index.php?title=Troubleshooting#HDRI_produces_scattered_bright_spots_.28fireflies.29). It's like your texture has many little "suns".

I'd probably bake with a solid orange emissive lava, which would have a hidden mesh renderer, but BakeryAlwaysRender component. The "real" lava would be a non-static object with your texture.

**Comment by laurentopia** [comment]
I did what you suggested and it works fine now. also in that other problematic scene.
thank you.
