### ISSUE TITLE
terrain optimization CPU only?

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#107]
it took too long so i canceled and went back to RTX and before cancelling i saw this
![image](https://user-images.githubusercontent.com/26075468/120747924-c00b7380-c4b6-11eb-93bf-6d5b47a9cec2.png)

**Comment by guycalledfrank** [comment]
There seems to be some weird combination of circumstances when Terrain Optimization gets stuck in a very long tracing loop, but I couldn't find the exact cause yet. If your terrains fir in your VRAM, there is no benefit of using the optimization.

**Comment by laurentopia** [comment]
I ended
