### ISSUE TITLE
artifacts during baking

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#109]
the third ring of leaves in this pine tree is darker 
depite normals are outwards like the rest
![image](https://user-images.githubusercontent.com/26075468/121629996-294c3300-ca31-11eb-8449-e8f471665731.png)

also present in RT
![image](https://user-images.githubusercontent.com/26075468/121629921-03bf2980-ca31-11eb-9547-62c6da017d1c.png)

import settings:
![image](https://user-images.githubusercontent.com/26075468/121630095-60badf80-ca31-11eb-8cac-7a4bf8a75d3c.png)

geometry:
[pine with borkned 3rd ring.zip](https://github.com/guycalledfrank/bakery-issues/files/6635799/pine.with.borkned.3rd.ring.zip)

**Comment by laurentopia** [comment]
change material with this
[borky mc borkbork.zip](https://github.com/guycalledfrank/bakery-issues/files/6635803/borky.mc.borkbork.zip)

**Comment by guycalledfrank** [comment]
![image](https://user-images.githubusercontent.com/7008423/122109599-377dc300-ce26-11eb-8d29-7bdfffba0d2c.png)

Unity doesn't really have its own .ma importer, it locates Maya on your machine and asks it to export a FBX. Can you export it for me? :D

**Comment by laurentopia** [comment]
[tree pine static.zip](https://github.com/guycalledfrank/bakery-issues/files/6671517/tree.pine.static.zip)

**Comment by guycalledfrank** [comment]
It looks like even before any baking, the third ring is borked already:

![image](https://user-images.githubusercontent.com/7008423/123516156-61937880-d6a3-11eb-90aa-cb1cd1ec2c99.png)

Interestingly it's the only ring with double-sided polygons, apparently they mess up with vertex normal smoothing:

![image](https://user-images.githubusercontent.com/7008423/123516173-7839cf80-d6a3-11eb-824e-37dc1938375f.png)

**Comment by laurentopia** [comment]
thanks I fixed that, I wonder how that got there...
