### ISSUE TITLE
Editor hangs when baking multiple scenes

### ISSUE THREAD

**Issue by fender** [guycalledfrank/bakery-issues#110]
Have turned on `Split By Scene` but whenever I bake 2 separate scenes, when going into playmode via the Editor and then selecting any game object with a `MeshRenderer` in the scene I get these warnings spammed in the console. 
![image](https://user-images.githubusercontent.com/1436470/122255875-795e4600-cec6-11eb-8d58-f584be00f8ab.png)

The editor locks up for about 60 seconds. It seems to be related to the `MeshRenderer` inspector (and most likely the part that shows a preview of which lightmap it uses.

Any tips on how to address this? @guycalledfrank 

I'm using version 1.9 and have applied all latest patches. The issue was occuring on 1.8 too.

**Comment by guycalledfrank** [comment]
Hi. Was the issue resolved somehow?

**Comment by fender** [comment]
> Hi. Was the issue resolved somehow?

It seemed to be something to do with having a Contribute GI flag checked on a Mesh Renderer in a prefab that is added as a child game object within another prefab. Perhaps a Unity bug? However, it's resolved now!
