### ISSUE TITLE
Keep fail to bake the scene - NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by wonkee-kim** [guycalledfrank/bakery-issues#111]
Bakery can't bake lightmaps with the below message and it's constant. (I tried to clean up temp files but still the same)

> NullReferenceException: Object reference not set to an instance of an object
> ftRenderLightmap+<RenderLightmapFunc>d__252.MoveNext () (at Assets/Standard Assets/Bakery/Editor/x64/Bakery/scripts/ftRenderLightmap.cs:5628)
> ftRenderLightmap.RenderLightmapUpdate () (at Assets/Standard Assets/Bakery/Editor/x64/Bakery/scripts/ftRenderLightmap.cs:3740)
> UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <c84609c921cb488481d7d8a5fcdf9588>:0)

**Comment by guycalledfrank** [comment]
Hi. Not sure line 5628 points to anything interesting anymore, so your version is probably behind some patches: https://github.com/guycalledfrank/bakery-csharp/blob/master/Editor/x64/Bakery/scripts/ftRenderLightmap.cs#L5628

Can you try updating? https://geom.io/bakery/wiki/index.php?title=Github_access

If there is still an error, please copy the new error message

**Comment by wonkee-kim** [comment]
Hi. After cleaning temp files and relaunch the project fixed it. I think temp files should be removed after terminating Unity project.

**Comment by guycalledfrank** [comment]
Probably, although the existence/lack of the temp files shouldn't affect the bake, so perhaps it was linked to something else?
