### ISSUE TITLE
RT preview looks different

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#113]
![image](https://user-images.githubusercontent.com/26075468/126029639-9df46f71-7458-4dc5-bae8-678a8128ecfe.png)

**Comment by guycalledfrank** [comment]
What should I look at? It looks like
- There is fog on the real-time screenshot.
- There is alpha testing on the real-time screenshot which lightmapper didn't take into account probably because it uses a non-standard map name.

**Comment by laurentopia** [comment]
I annotated
could be the indirect # that's >1 combined with backface GI of 4
![image](https://user-images.githubusercontent.com/26075468/126115428-d7a947b3-2d41-4cbf-8d71-19adb2940cdd.png)

**Comment by laurentopia** [comment]
(there is post process)

**Comment by guycalledfrank** [comment]
Can confirm, values larger than 1 do differ. I'd avoid such values, as it means your trees emit more light than they receive.

After some investigation seems like the reason for this is that I compress albedo and emission into single float to save bandwidth in RTPreview.

Fixed (same bandwidth, just moved weight multiplication elsewhere): https://github.com/guycalledfrank/bakery-rtpreview-csharp/commit/6dc18763f24c51dbe7ce4c3172535efa9cdc9af1

**Comment by laurentopia** [comment]
Thanks!
