### ISSUE TITLE
bakeryURPvolume shader compile error

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#117]
Build target = switch which uses a flavor of vulkan.

![image](https://user-images.githubusercontent.com/26075468/126853425-64a6b02c-c70a-40e2-ad4b-11843eb2548c.png)

**Comment by guycalledfrank** [comment]
Seems like you're using an older package. SAMPLE_TEXTURE2D was removed from later releases. Try latest? https://drive.google.com/file/d/14gKWpEl_adF0euOMHLbGBcF7Fqm310Jb/view?usp=sharing
