### ISSUE TITLE
Suggestion: A tool to bake multiple scenes one after another

### ISSUE THREAD

**Issue by pedropla** [guycalledfrank/bakery-issues#127]
I've found that sometimes I need to rebake quite a few scenes. For example if some shared asset has changed, or perhaps I need to change some lighting modifier in bakery across them. It would be very useful if there was a tool to select scenes to bake, and then just let it bake them all one after another. If this could be made in a way that you could see at a glance each scene's bakery settings and edit them before sending it to bake all the scenes that would be great. That way I wouldn't have to be at my computer making sure one scene is baked, then the next, etc. I could just leave it running for an hour or whatever it takes.

**Comment by guycalledfrank** [comment]
There is batch scene baker: https://geom.io/bakery/wiki/index.php?title=Community_extensions#Batch_scene_baker

**Comment by pedropla** [comment]
Awesome! Thanks! I must have missed that. Perhaps it can be included in the main bakery?

**Comment by guycalledfrank** [comment]
Yeah maybe I should do that :)

**Comment by guycalledfrank** [comment]
Now a part of the main repository, will be also included in the store package:
https://github.com/guycalledfrank/bakery-csharp/commit/87126f5aa178238ee89943aa4cba48f646026187
