### ISSUE TITLE
Bicubic filtering uses wrong texel size for the main lightmap when using SH

### ISSUE THREAD

**Issue by z3y** [guycalledfrank/bakery-issues#129]
Bakery allows you to set different lightmap size for directional lightmaps
![image](https://user-images.githubusercontent.com/33181641/150422474-6522bca6-46a5-4589-a0f7-f87b13c7c1c8.png)

Bicubic filtering is using _RNM0_TexelSize for all 4 textures when using SH mode

If the directional lightmaps have a lower resolution, the main lightmap(L0) is sampling bicubic with wrong texel size

**Comment by guycalledfrank** [comment]
Hmm makes sense, sounds problematic.
Actually BakerySH() doesn't even have to sample the main lightmap, as it's already sampled by the built-in code, and if Shader Tweaks's bicubic filtering is also enabled, it should all work (Tweaks use tex.GetDimensions to get texel size).

So hopefully it's all what's needed: https://github.com/guycalledfrank/bakery-csharp/commit/682c0a4a60b862d225ec7c1a000abe68773aca1d
