### ISSUE TITLE
Harsh borders between meshes

### ISSUE THREAD

**Issue by m-s-malt** [guycalledfrank/bakery-issues#131]
After baking a scene there are harsh and incredibly obvious divides between mesh prefabs, as seen here along the sections of one modular wall.
![image](https://user-images.githubusercontent.com/99354624/153264460-67b5a301-12fc-4fee-9e07-6d991ea04c70.png)
Settings used are the below, baking with RTX on on an NVidia 3090 GPU
![image](https://user-images.githubusercontent.com/99354624/153264639-618256df-edc6-4533-90da-ad9c5bff9d09.png)

**Comment by m-s-malt** [comment]
It should be mentioned that this issue doesn't occur when using 'Full Lighting' render mode, although using 'Full Lighting' mode means that non-static objects in the scene (such as the door in the below screenshot) become completely black.
![image](https://user-images.githubusercontent.com/99354624/153280389-abb6d3ff-c2da-4637-8ad7-bbd618694ad9.png)

**Comment by m-s-malt** [comment]
An update to this, I switched all lights to use 'Direct and Indirect' baked contribution which solved the problem of the blocky wall lightmaps... but now I'm having some very strange behaviour with non-static objects. The below screenshots show literally two sides of the same door. You can see that one side is recieving lightmap data while the other is totally black.
![image](https://user-images.githubusercontent.com/99354624/153721549-d6906332-e91f-4651-b884-57282ebc75be.png)
![image](https://user-images.githubusercontent.com/99354624/153721587-e5609dae-682e-432a-90a4-88e4a385e0c5.png)

**Comment by guycalledfrank** [comment]
Hi. Sorry for the delay. So in which mode the seam between walls was visible? Is it Shadowmask? Any directional mode? Did you get any warnings about too many overlapping lights before baking?

How is the door lit? Is it using light probes? How are they positioned? Did you also check "occlusion probes"?

**Comment by guycalledfrank** [comment]
Hi. Sorry for the delay. So the seam between walls was visible in Indirect mode only? Does it appear if you turn off all your real-time lights? Seems like that the seam comes from real-time light per-object limit in Unity forward renderer (should go away if you increase pixel light count in Quality settings).

How is the door lit? Is it using light probes? How are they positioned? Did you also check "occlusion probes"?

**Comment by m-s-malt** [comment]
Hi, this issue was found using indirect mode but also occurred in shadowmask when I tested that. Occlusion probes were disabled when I took this screenshot but I did turn them on later, although it didn't make any difference.
I later resolved this by setting all lights to use 'direct and indirect' baked contribution which fixed the issue. The door was lit using light probes, however I did discover later that the lightprobes groups on the doors were at an X rotation of -90. Changing this to 0 also resolved issues with the lighting on the doors.
I'll mark this issue as closed now since I found a solution.

**Comment by guycalledfrank** [comment]
"Direct and Indirect' fixing the issue means completely disabling real-time light effect. Meaning the seams were likely caused by real-time lights, not lightmaps. So please check that and your Quality settings if you'll decide to use indirect/shadowmask again.

Light Probe Group rotation shouldn't have any effect. Only final transformed probe position is used, so it's weird... if you'll be able to reproduce anything like this on a small scene and send it to me, I'll test it.

**Comment by m-s-malt** [comment]
Is there a value you would recommend setting pixel light count to? Do scenes need to be rebaked after changing this value?

**Comment by guycalledfrank** [comment]
The more real-time lights intersect on a single object, the higher value you need. Alternatively, using a deferred rendering path should fix it. This issue is not related to lightmaps/baking.

**Comment by m-s-malt** [comment]
Ok, reverting the lights back to indirect only and increasing the pixel light count has resolved the issue.
