### ISSUE TITLE
Lightmap stops working after baking reflection probes and entering play mode

### ISSUE THREAD

**Issue by artnas** [guycalledfrank/bakery-issues#143]
Hey. Baking a lightmap works as expected, but after baking reflection probes, it only works in edit mode. Play mode makes the lightmap fully black.

This is a scene, not a prefab

Baked lightmap (looks the same in play mode)

![image](https://user-images.githubusercontent.com/14143603/213209597-458b49ad-a173-4de7-999a-f5c8d5bf2ccd.png)

After baking reflection probes this appears

![image](https://user-images.githubusercontent.com/14143603/213210230-79525185-a5d3-4760-8bb1-84737d52c0c9.png)

Baked lightmap with reflection probes (Edit mode)

![image](https://user-images.githubusercontent.com/14143603/213209732-0bcd4ad5-eaa5-4c80-a462-573799a4f402.png)

Baked lightmap with reflection probes (Play mode)

![image](https://user-images.githubusercontent.com/14143603/213209790-683200f2-4303-4d2b-a3c1-a698c3ad3465.png)

Am I missing something here or is this a bug?

**Comment by guycalledfrank** [comment]
Possibly related to some very recent Unity editor bug, this was addressed in v1.95:

![image](https://user-images.githubusercontent.com/7008423/213219952-543bc7b3-315b-4c32-9ab2-bc69d5d5a4b4.png)

Are you sure you're on the latest version? Hovering over the blue "Bakery" text will show you the version number.

**Comment by artnas** [comment]
I just downloaded the asset today (v1.95) and patched it using "Check for patches". I'm on Unity 2021.3.15

Seems like this is the same issue as this: https://forum.unity.com/threads/bakery-gpu-lightmapper-v1-95-rtpreview-released.536008/page-130#post-8737716

The lightmaps indeed dissapear after entering play mode
![image](https://user-images.githubusercontent.com/14143603/213241487-3c76f06a-0f3e-4ffa-ad2f-c2152e11398d.png)

**Comment by guycalledfrank** [comment]
Weird... I can't reproduce it on Sponza, but I don't have the exact Unity version. Can you try if this works:
- Create an empty scene with a reflection probe, save it
- Bake this reflection probe using the built-in bake button
- Take the newly generated lighting data asset, and replace emptyLightingData.asset with it
- Delete lighting data asset in your main scene
- Re-render reflection probes via Bakery in your main scene

Will this work?

**Comment by artnas** [comment]
I created a new scene, added a reflection probe and baked it. Scene with reflection probe

![image](https://user-images.githubusercontent.com/14143603/213246798-f0728be6-07bd-4e93-b7cd-1fef2df622b3.png)

Then took the new lighting data asset and selected it in my main scene

Main scene, edit mode

![image](https://user-images.githubusercontent.com/14143603/213246589-218eba5c-fea4-48a8-bac6-ca54f92cf399.png)

Main scene, play mode

![image](https://user-images.githubusercontent.com/14143603/213246640-428dc9db-7e9f-4e1e-8600-343c5b20e64c.png)

The result seems to be the same

**Comment by guycalledfrank** [comment]
OK, I don't know then. Can you make a simplified copy of this project (e.g. just this scene, no material textures, scripts, etc... actually can even skip most props except for the walls) and send it to me for debugging? (just make sure it opens/bakes/shows the bug)

**Comment by guycalledfrank** [comment]
Reproduced it today on another project in Unity 2021. Can you try the latest patch now?

Or, just add this one line to the Start() of ftLightmapsStorage.cs:

![image](https://user-images.githubusercontent.com/7008423/214419350-f54ef152-4486-40b2-9f5c-a5a5f8aaaf4c.png)


https://github.com/guycalledfrank/bakery-csharp/commit/d7f0c9cf79c3bcfcf2c3c6de6434cba34800874f

It seems that since Unity 2021, if you have a lighting data asset in the scene (which is created if you have light/reflection probes), then there is a chance it will try to reload it after Awake() (but before Start()).

**Comment by artnas** [comment]
It works. Thank you!
