### ISSUE TITLE
The "Cancel" Button doesn't cancel the action for baking at all.

### ISSUE THREAD

**Issue by CrossVadar** [guycalledfrank/bakery-issues#147]
Instead of it really cancels the action like it should, it just do a bake cycle and saves nothing at all. Have to force close Unity to stop it.

**Comment by guycalledfrank** [comment]
The cancel behaviour can be different depending on the current action. What was written on the progressbar when you were trying to cancel?

**Comment by CrossVadar** [comment]
It continues to export the scene and rendering lightmaps.

**Comment by guycalledfrank** [comment]
I opened Sponza example and tried cancelling at "preparing", "surface shaded colors", "adjusting sample positions", it worked. Not always immediately, but it cancelled the process.

I need more specifics about the moment you cancel (what is on the progress bar).

If you can record a little video/gif, that would also help.

**Comment by CrossVadar** [comment]
I m sorry about not clear enough, it's when I haven't save the changes and click on it , then the cancel will not work.
https://user-images.githubusercontent.com/70632575/225928957-d04f26a7-e2bc-4c7a-8de5-736814e6467b.mp4

**Comment by guycalledfrank** [comment]
Ah, indeed. An oversight :)
Fixed: https://github.com/guycalledfrank/bakery-csharp/commit/c08912120ddb3ee6f451d0ed5e5a5407001719d2
Please try updating via the patcher: https://geom.io/bakery/wiki/index.php?title=Github_access

**Comment by CrossVadar** [comment]
Thank You. ; )
