### ISSUE TITLE
Managed to break the Github Invite

### ISSUE THREAD

**Issue by Zdufault** [guycalledfrank/bakery-issues#149]
Hey! When trying to access the github and registering my invoice I got thrown an error/something went wrong when I submitted. Now when I try again it says my invoice is already registered with another account but I know I haven't registered it to something else.

I got into the RTPreview github fine though! Just wanted to try to get some newer builds as I'm running into some light probe baking errors where "Scene geometry/layout changed since last full bake" even though it's right after I ran the bake and haven't moved or done anything else.

Sorry if this isn't the proper channel to reach out through, and appreciate the help in advance!

**Comment by guycalledfrank** [comment]
1. Do you remember the error that the invite form showed you?
2. Please email your invoice to me, I'll check if it's added there somehow. I can't find your github name in the database.
3. What light probe mode are you using (L1/Legacy)?

**Comment by Zdufault** [comment]
Off the top of my head nah sorry, I went through it and figured I'd try again late last night. I know it was some text that was something along the lines of "couldn't find _____" and then threw me to a github 404 which I assume was the link to the private github but I wasn't hooked in so. I'm pretty sure I didn't capitalize my username that first try which might of messed things up as well.

I'll send the invoice your way thanks!

And I'm using L1! It became a more consistently recent issue when things either got a bit big or maybe when I set Asset UV processing to Remove UV adjustments? Not sure if either would mess with it, but I did figure out if I save and quit out after a lighting bake, then open the project once more it seems to bake the light probes then.

**Comment by guycalledfrank** [comment]
If you're using L1, then, in fact, the probes are always baked together with lightmaps. So they're already done :)

**Comment by Zdufault** [comment]
Oh, actually then that makes sense then duh. Looking over that again it does say that in the manual haha. I must of looked over that way early on when I knew even less and never double checked that setting so.

The new build seems to be running smoothly so far as well then so should be everything from me! 

Thanks again for the help!
