### ISSUE TITLE
Denoise and RTX mode error

### ISSUE THREAD

**Issue by Reguluz** [guycalledfrank/bakery-issues#15]
Denoise error
![](https://cdn.discordapp.com/attachments/648434699785601027/713282581826764801/unknown.png

RTX error: I have just installed OptiX SDK 7.0 and have already reset my PC. My video card is Geforce 2070.
![](https://cdn.discordapp.com/attachments/648434699785601027/713283981532987512/unknown.png)

**Comment by guycalledfrank** [comment]
You don't need to install OptiX SDK, just update the driver: https://www.nvidia.com/Download/index.aspx?lang=en-US

Also make sure that you have following files in the same folder as ftrace.exe:
optix.1.dll
optix.51.dll
optix.6.0.0.dll
optix_denoiser.51.dll
optix_denoiser.6.0.0.dll
cudart32_91.dll
cudart64_90.dll
cudart64_91.dll
cudnn64_7.dll

**Comment by Reguluz** [comment]
> You don't need to install OptiX SDK, just update the driver: https://www.nvidia.com/Download/index.aspx?lang=en-US
> 
> Also make sure that you have following files in the same folder as ftrace.exe:
> optix.1.dll
> optix.51.dll
> optix.6.0.0.dll
> optix_denoiser.51.dll
> optix_denoiser.6.0.0.dll
> cudart32_91.dll
> cudart64_90.dll
> cudart64_91.dll
> cudnn64_7.dll

Solved! thanks a lot^^
