### ISSUE TITLE
Bakery Real-Time Preview - ftrace - Type Mismatch Error

### ISSUE THREAD

**Issue by danieldownes** [guycalledfrank/bakery-issues#153]
I've just purchased RTP, however I've not yet been able to get this working, I get this error:

![image](https://github.com/guycalledfrank/bakery-issues/assets/1720388/5094bc4c-a190-49d1-840d-d88969ce85ce)

**Comment by guycalledfrank** [comment]
It seems like your lightmapper version is older than your RTPreview (Possibly even older than the current Asset Store version). Please try updating it. You can use the built-in patcher: https://geom.io/bakery/wiki/index.php?title=Github_access

**Comment by danieldownes** [comment]
Yep that got it. Could add a santity check if rtp is version dependant on a bakery version, would make for a better error message.

**Comment by guycalledfrank** [comment]
Yeah, good idea, I'll add it :)

**Comment by guycalledfrank** [comment]
Added 
https://github.com/guycalledfrank/bakery-rtpreview-csharp/commit/7b781acb836553128391be0f3769401e4f3c83b5
