### ISSUE TITLE
SH Direction mode broken in build after load other scene (Android)

### ISSUE THREAD

**Issue by Arhistratig72** [guycalledfrank/bakery-issues#155]
I have builded apk (Android build) with two scenes. Light baked with SH direction mode + light probes. Both scenes has completly different meshes, optimize meshes or shader striping is off (tryed all possible variations). When I load to other scene by SceneLoad() my lighting became corrupted. Looks like SH maps get replaced by other from previous scene or missing. But in Editor everything looks good.

![photo_2023-10-02_20-26-30](https://github.com/guycalledfrank/bakery-issues/assets/44098428/5f8df406-8525-4817-b868-6ed476701379)
![photo_2023-10-04_20-33-16](https://github.com/guycalledfrank/bakery-issues/assets/44098428/b5a10208-fe7d-4c8d-9734-eb68c28f3044)

**Comment by guycalledfrank** [comment]
OK, weird, do you load the scenes asynchronously at runtime? Can you try calling ftLightmaps.RefreshFull() after the scene is fully loaded? Also, does it happen to any scene that is open at the time of building?

**Comment by Arhistratig72** [comment]
Asynchronously or not - dont fix the issue, but yes , in already packaged build at runtime I load scenes, and next one will be corrupted always. I will try to call  ftLightmaps.RefreshFull(), thanks

**Comment by guycalledfrank** [comment]
BTW, did it help?

**Comment by Arhistratig72** [comment]
Hello, I was able to look only now. It helped, thanks.
