### ISSUE TITLE
Realtime Preview dont work, throw error

### ISSUE THREAD

**Issue by Arhistratig72** [guycalledfrank/bakery-issues#157]
Hello, I can bake the whole lighting on scene, but somehow I cant use realtime preview. Everytime when I press preview its throw me error and destroy scene editor camera..All geometry its obj models with uv and settings like on screenshot.
All lights is AreaLight also like on screenshot.

![image (8)](https://github.com/guycalledfrank/bakery-issues/assets/44098428/08923414-7c8d-4908-9882-12b8f2439e8f)
![image](https://github.com/guycalledfrank/bakery-issues/assets/44098428/e47a26e6-4243-41c7-9bc9-3682895ee650)
![image](https://github.com/guycalledfrank/bakery-issues/assets/44098428/82b3e095-bc8f-4108-941a-d9d75226efe5)

**Comment by guycalledfrank** [comment]
Looks like you have a mismatch between lightmapper/preview versions.
Please update both to the latest version: https://geom.io/bakery/wiki/index.php?title=Github_access

**Comment by Arhistratig72** [comment]
Thanks for fast respose!
Its says I already have last one.
![image](https://github.com/guycalledfrank/bakery-issues/assets/44098428/3d3ce78f-ef16-40bb-99cf-3d26aa0cbec4)

**Comment by guycalledfrank** [comment]
Did you update BOTH the preview and the lightmapper?

**Comment by Arhistratig72** [comment]
> Did you update BOTH the preview and the lightmapper?

Yes

**Comment by Arhistratig72** [comment]
> Did you update BOTH the preview and the lightmapper?

Seems like Autopatcher doesnt update both.. just replace files by new one from git. And it works. Thanks!
