### ISSUE TITLE
Waiting for user code in BakeryEditorAssembly.dll to finish exectuging and it spins forever 

### ISSUE THREAD

**Issue by RubDevRG** [guycalledfrank/bakery-issues#158]
![Screenshot 2024-04-23 175501](https://github.com/guycalledfrank/bakery-issues/assets/167897652/57bd2d20-1110-4e08-be7d-2c2e7f1d31f0)

Endless Loop even after 1hour + wont finish. Waiting for user code in BakeryEditorAssembly.dll to finish exectuging and it spins forever

**Comment by guycalledfrank** [comment]
See this: https://geom.io/bakery/wiki/index.php?title=Troubleshooting#.22Exporting_scene_-_preparing.22_is_taking_too_long

**Comment by RubDevRG** [comment]
Thank you that helped.
