### ISSUE TITLE
MonoSHSpecGraph missing reflection in URP.

### ISSUE THREAD

**Issue by othercrow** [guycalledfrank/bakery-issues#161]
The Bakery MonoSHSpecGraph shader is missing reflections in URP.

- Unity 2022.3.44f1
- URP 14.0.11
- Bakery 1.96 

Possibly relevant:

- I do have the common "Lighting data asset is incompatible with the current Unity version." error message.
- The first time I open a scene in the editor with baked lighting, the lighting is all black. Then I open it a second time and lightmaps load as expected.
- Some Bakery shaders like specular volume-lit shaders do have reflection still.

Here's a quick comparison of the URP Lit shader vs MonoSHSpecGraph. They _should_ both be reflective.
![bakerypls](https://github.com/user-attachments/assets/7a8a6287-3eb5-4c87-bc47-78d618ab2007)

**Comment by guycalledfrank** [comment]
I'm not really supporting MonoSHSpecGraph anymore. All the separate graphs were merged into BakeryURPLit which is easier to use (and easier to debug/fix). You can grab latest URP graph updates here: https://geom.io/bakery/wiki/index.php?title=Bakery_-_GPU_Lightmapper
Set BakeryURPLit mode dropdown to MonoSH, and it should do the job (reflections included). Can you check it?

**Comment by othercrow** [comment]
![image](https://github.com/user-attachments/assets/22bdb287-0e69-4543-84ff-94795431936d)
Ok thanks I upgraded and swapped everything to BakeryURPLit.
Reflections are back but shadows in the reflections seem overly harsh on metallic objects.
Are there recommended settings for the section I've marked in red?
All of my materials are variants of the one shown here.

**Comment by othercrow** [comment]
Possibly relevant:
Lightmaps disappear often after loading a scene or moving an object. Loading the scene again restores them.
Before moving the highlighted pot:
![image](https://github.com/user-attachments/assets/4feb4848-4178-40dd-99e0-4096eeb8594f)
After moving the pot slightly:
![{7B11C7E1-E34B-47E5-877C-7BF928DED942}](https://github.com/user-attachments/assets/007a1f25-332c-49cb-a901-307e99807f84)

**Comment by othercrow** [comment]
Solved the problem with too-dark reflections.
There seems to be an underlying bug (with Unity?) that causes Reflection Probes that previously had custom cubemaps to not respect switching back to Baked type.
So no matter how many times I baked reflection probes, objects were still getting the custom cubemap reflections from several weeks ago.

This fixed it:

1. Select all Reflection Probes.
2. Change Type from Baked to Custom.
3. Set Cubemap: None.
4. Change Type back from Custom to Baked.
5. Bake reflection probes.

Still having issues with lightmaps in general loading as black the first time but that's a separate issue.

**Comment by guycalledfrank** [comment]
>Reflections are back but shadows in the reflections seem overly harsh on metallic objects.

Metallic surface are basically full-reflection. If you use "Lightmap specular as reflection occlusion", you narrow the reflection with SH specular mask... and there is no diffuse to fill the void. If the only thing you got is the reflection, then occluding it leaves nothing. So really it shouldn't be used with metallic surfaces. 

>Lightmaps disappear often after loading a scene or moving an object. Loading the scene again restores them.

Do you, by any chance, have "reload scene" disabled? https://geom.io/bakery/wiki/index.php?title=Troubleshooting#Lightmaps_disappear_on_play

>There seems to be an underlying bug (with Unity?

OH! I didn't know that.

>Still having issues with lightmaps in general loading as black the first time but that's a separate issue.

Can you check if it's still the case even when using the latest github patch?
