### ISSUE TITLE
ftBatchSceneBake doesn't save the result of each bake

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#19]
repro: add scenes to the array, keep all the checkboxes, Batch Bake
result: scenes have no baked lightmaps
expected: scenes are baked

**Comment by guycalledfrank** [comment]
I could not reproduce it. Any console errors during the bake?

**Comment by laurentopia** [comment]
yes a few
![image](https://user-images.githubusercontent.com/26075468/97928982-fd3f3580-1d1c-11eb-9d05-9c3c16b36d8d.png)
![image](https://user-images.githubusercontent.com/26075468/97929638-755a2b00-1d1e-11eb-9936-26f022e3fa43.png)

**Comment by guycalledfrank** [comment]
Ah yes. Just update from github first please: https://geom.io/bakery/wiki/index.php?title=Github_access
