### ISSUE TITLE
when pressing render light probes after a render lightmaps it detects changes of layout and rebakes everything

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#20]
before the save prompt it should do this check

**Comment by guycalledfrank** [comment]
Please update from github:
https://geom.io/bakery/wiki/index.php?title=Github_access

**Comment by laurentopia** [comment]
still ticking
![image](https://user-images.githubusercontent.com/26075468/97930556-81df8300-1d20-11eb-833c-5be50cf76851.png)

**Comment by guycalledfrank** [comment]
Is it
- Right after you did normal Render in the same scene? (Without baking other scenes in between?)
- After you updated?

**Comment by laurentopia** [comment]
Yes right after a normal render.
