### ISSUE TITLE
Error generating on RTX 3070

### ISSUE THREAD

**Issue by BovineOx** [guycalledfrank/bakery-issues#29]
Hi There

I tried using Bakery again as the preview GPU lightmapper in Unity is still too flaky, possibly for similar reasons.

The bake fails straight away, even on very low settings (see screenshot). I suspect that the CUDA library used is older than the RTX 3070 but obviously that's little more than an educated guess.

Thanks

![image](https://user-images.githubusercontent.com/73857041/99180823-898c2800-2721-11eb-94d6-eece7ef15cba.png)

**Comment by guycalledfrank** [comment]
Please use RTX mode: https://geom.io/bakery/wiki/index.php?title=Manual#RTX_Mode

RTX version of the lightmapper is built using OptiX 6 and seems to work fine on 30x0 GPUs.
Non-RTX version is built using OptiX 5.1 and somehow appears to be not working there.

**Comment by BovineOx** [comment]
Thank you for the super swift support. I had read something about RTX mode and then couldn't find it (wood for trees!), I am baking as I type and it has actually started the bake instead of barfing as it did previously, so fingers crossed this works, looking good so far.

Bakery was always so much faster and more reliable than the preview GPU which still borks right away and produces ugly seams, though this was to do with the denoise algorithm I am told.

Bake completed, so that took minutes on a large scene. Looks like it's going to take as long to impor the lightmaps!

Thanks again.

**Comment by guycalledfrank** [comment]
Did you find the RTX checkbox in the end or did it manage to work without it? Optix denoiser worked OK?

**Comment by BovineOx** [comment]
Yes, I found the RTX checkbox this time, I didn't change any denoise settings and it's worked every time.
