### ISSUE TITLE
won't bake, brand new github version

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#31]
![image](https://user-images.githubusercontent.com/26075468/99207204-3393a080-2772-11eb-9acd-e3c38dc76004.png)

**Comment by laurentopia** [comment]
![image](https://user-images.githubusercontent.com/26075468/99211203-ab66c880-277c-11eb-9a16-b7a795020c6d.png)
`Exception caught: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <9577ac7a62ef43179789031239ba8798>:0 
  at ftBuildGraphics+<ExportScene>d__203.MoveNext () [0x045e1] in Z:\McDROID_2020.1 URP\Assets\Scripts\Plugins\Bakery\Editor\x64\Bakery\scripts\ftBuildGraphics.cs:6083 
UnityEngine.Debug:LogError(Object)
<ExportScene>d__203:MoveNext() (at Assets/Scripts/Plugins/Bakery/Editor/x64/Bakery/scripts/ftBuildGraphics.cs:6387)
<RenderLightmapFunc>d__261:MoveNext() (at Assets/Scripts/Plugins/Bakery/Editor/x64/Bakery/scripts/ftRenderLightmap.cs:4760)
ftRenderLightmap:RenderLightmapUpdate() (at Assets/Scripts/Plugins/Bakery/Editor/x64/Bakery/scripts/ftRenderLightmap.cs:4164)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
`

`KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <9577ac7a62ef43179789031239ba8798>:0)
ftBuildGraphics+<ExportScene>d__203.MoveNext () (at Assets/Scripts/Plugins/Bakery/Editor/x64/Bakery/scripts/ftBuildGraphics.cs:6388)
ftRenderLightmap+<RenderLightmapFunc>d__261.MoveNext () (at Assets/Scripts/Plugins/Bakery/Editor/x64/Bakery/scripts/ftRenderLightmap.cs:4760)
ftRenderLightmap.RenderLightmapUpdate () (at Assets/Scripts/Plugins/Bakery/Editor/x64/Bakery/scripts/ftRenderLightmap.cs:4164)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <20b79eb59c0f467d8b1106b2110bc953>:0)
`

**Comment by laurentopia** [comment]
what i tried:
cleared baked data
![image](https://user-images.githubusercontent.com/26075468/99211349-f1bc2780-277c-11eb-989b-c78004ae161e.png)

**Comment by guycalledfrank** [comment]
Hmm did you update from BOTH -csharp and -compiled repositories?

**Comment by laurentopia** [comment]
yes

**Comment by guycalledfrank** [comment]
Maybe try a fresh project? It seems other users are baking fine.

**Comment by laurentopia** [comment]
It Fixed itself
