### ISSUE TITLE
URPVolumeSpecGraph no reflection

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#38]
![image](https://user-images.githubusercontent.com/26075468/100829696-df95e680-3416-11eb-9bbd-aed8606629f3.png)
with these settings
![image](https://user-images.githubusercontent.com/26075468/100829720-ec1a3f00-3416-11eb-8f13-41122df6beed.png)
this is UTP/lit
![image](https://user-images.githubusercontent.com/26075468/100830147-d9543a00-3417-11eb-89b7-f608fdbfa451.png)

**Comment by laurentopia** [comment]
with the same parameter of metallicity and smoothness
so the question is how do i get urpvolumspec to have the same reflectance?

**Comment by laurentopia** [comment]
and on second look it appears that bakeruurpvolumspec doesn't grab the reflection from the refprobe but instead grabs the sky map

**Comment by laurentopia** [comment]
proof:
reflection probe intensity = 5
![image](https://user-images.githubusercontent.com/26075468/100831916-9300da00-341b-11eb-993b-2d9ff9472896.png)

reflectionprobe intensity = 1.5
![image](https://user-images.githubusercontent.com/26075468/100831936-a0b65f80-341b-11eb-8ee4-ca5218b9da8f.png)

= same

so whatever bakedurpvolumespec is reflecting ain't the refprobe

**Comment by guycalledfrank** [comment]
URP is quite horrible when it comes to extending it.

Anyway, the problem seems to happen because of my hacky way of replacing built-in GI which involves setting Occlusion to 0 (essentially multiplying built-in GI by zero). Turns out, it also multiplies reflection probes by zero.

As there is no custom GI input in the PBR Graph, I added reflection probe sampling with PBR weighting to the graph. Please try this version: https://drive.google.com/file/d/14gKWpEl_adF0euOMHLbGBcF7Fqm310Jb/view?usp=sharing

**Comment by laurentopia** [comment]
Thanks!

I see you now feed emission with reflection probe. I think there is a problem with the math as suddenly the brightness of emission objects is much much less, I need to 3x its value and then the hue changes. 

By the way, does the shader compiler or execution skip chunks of shader code if the values are zeroed out. For example if you don't connect anything to transparency, AO or metal etc...

**Comment by guycalledfrank** [comment]
Comparing to standard URP Lit shader, my graphs may have a different way of scaling the emission (just a linear multiplier). Not sure about hue, there shouldn't be any difference.

I really hope it skips built-in GI/refprobes as occlusion=0 is a constant compiled into the shader.

**Comment by laurentopia** [comment]
It looks like it skips a lot
![image](https://user-images.githubusercontent.com/26075468/101122010-557c8800-35a6-11eb-9fae-7ce44ca07649.png)
a compiled PBR with occlusion = 0 is 2.9MB
same with occlusion=1 is 3.2MB

**Comment by guycalledfrank** [comment]
That sounds good! Shouldn't calculate the reflection twice then.
