### ISSUE TITLE
Can't bake light probes in legacy mode

### ISSUE THREAD

**Issue by Zurigan** [guycalledfrank/bakery-issues#43]
This error gets thrown:
![](https://cdn.discordapp.com/attachments/648434699785601027/786350329569869854/unknown.png)

Using a 3070 GPU, Unity 2020.1.16

**Comment by guycalledfrank** [comment]
This looks like you're on a 3xxx GPU with RTX mode disabled. You should enable it. Did you run "Bakery -> Utilities -> Detect optimal settings?"

**Comment by Zurigan** [comment]
The same error happens with RTX mode enabled or disabled.

**Comment by guycalledfrank** [comment]
Oops, sorry. indeed, Legacy light probe render didn't switch itself to RTX.

Fixed: https://github.com/guycalledfrank/bakery-csharp/commit/9debe3c91d6eb7e57472e0582afa4aa0f42a4dcd

You can download the github patch (https://geom.io/bakery/wiki/index.php?title=Github_access) or just replace two instances of "ftrace" (WITH quotes) with ftraceExe (without quotes) in ftRenderLightmap.cs

**Comment by Zurigan** [comment]
Different error now :)

FileNotFoundException: Could not find file "C:\Users\Ben\AppData\Local\Temp\frender\probes.dds"
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <9577ac7a62ef43179789031239ba8798>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) (at <9577ac7a62ef43179789031239ba8798>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
System.IO.File.Open (System.String path, System.IO.FileMode mode, System.IO.FileAccess access) (at <9577ac7a62ef43179789031239ba8798>:0)
ftRenderLightmap+<RenderLightProbesFunc>d__256.MoveNext () (at Assets/Editor/x64/Bakery/scripts/ftRenderLightmap.cs:3889)
ftRenderLightmap.RenderLightProbesUpdate () (at Assets/Editor/x64/Bakery/scripts/ftRenderLightmap.cs:2350)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <c84609c921cb488481d7d8a5fcdf9588>:0)

**Comment by Zurigan** [comment]
OK! This is looking a bit better now ... with L1:

![image](https://user-images.githubusercontent.com/3914073/101825272-433ca580-3ae2-11eb-9b87-5c284cd805f8.png)

With Legacy:

![image](https://user-images.githubusercontent.com/3914073/101825028-ed67fd80-3ae1-11eb-9396-12c70f8ac481.png)

So ... still ringing but now mostly the right color ... think this might be at the level where players won't notice :)

**Comment by guycalledfrank** [comment]
That's it, I guess :(. I couldn't find a better way to convolve spherical harmonics when bright lights are used. Non-linear light probe fix in the shader is also fixing it all neatly without needing to change input values.
