### ISSUE TITLE
No way to support Sprites or transparent textures with Bakery Volumes & URP

### ISSUE THREAD

**Issue by Zurigan** [guycalledfrank/bakery-issues#44]
I'm still learning shaders/lighting/etc. Apologies if this is something obvious or rehashing old ground.

For context: I'm building a 2.5D game that's using Sprites & Spine entities (trees, characters), looks like this:

![image](https://user-images.githubusercontent.com/3914073/101821252-93186e00-3adc-11eb-8345-1f1a84c9ecec.png)

The trees are Sprites, ground is a Plane with Bakery baked shadows on it, the character is made in Spine (a mesh renderer).
 
I'm trying to find a more performant way to light everything ... light probes & Bakery were causing headaches so I'm trying out Bakery Volumes instead. With the shader set to BakeryURPVolumeGraph (but ... surface changed to transparent, alpha clip set to 0.01, two-sided enabled in PBR master node) the scene looks like this:

![image](https://user-images.githubusercontent.com/3914073/101821982-8c3e2b00-3add-11eb-94fa-a1c236a440a4.png)

So ... lighting from the Volume is working (cool!) but Sprites are opaque and seem to ignore the shader alpha clip. The Spine character works a little better in that some of the images from the atlas are being drawn as expected ... the blue/green blocks are from overlaid 'glows', this is the atlas:

![image](https://user-images.githubusercontent.com/3914073/101822710-9f9dc600-3ade-11eb-9c4e-8a95977c269a.png)

So ... just to confirm what's happening here ... https://geom.io/bakery/wiki/index.php?title=Manual#Opacity does mention that Bakery only uses cutout (right?) so ... am I completely out of luck here? There's just no support for transparency?

**Comment by guycalledfrank** [comment]
Lightmapper itself shouldn't have a problem with opacity, it's just the URP shader, I didn't make a transparent version.  Did you switch surface on the "PBR Master" node? And by alpha clip, did you mean the "alpha" value on it? The latter is not the clip value, but the actual input alpha value. Connecting the alpha channel from BaseColor to it seems to work:

![image](https://user-images.githubusercontent.com/7008423/101825929-5df13780-3b3f-11eb-9e46-599be666d05f.png)

![image](https://user-images.githubusercontent.com/7008423/101825952-63e71880-3b3f-11eb-8111-1138891fcf49.png)

**Comment by Zurigan** [comment]
Ah, I was missing the Alpha input into the PBR Master node. That fixed the transparency issues. Great!

Now seeing some other issues, will log those separately!
