### ISSUE TITLE
new volume shader graph has problems

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#45]
just loaded it in the project and now getting this red stuff
![image](https://user-images.githubusercontent.com/26075468/101847427-18654800-3b08-11eb-9e33-2e23fbca41c2.png)

**Comment by laurentopia** [comment]
this shader
![image](https://user-images.githubusercontent.com/26075468/101848462-6713e180-3b0a-11eb-8823-e6c9fc346416.png)

**Comment by guycalledfrank** [comment]
Does it happen with the non-spec version?

**Comment by laurentopia** [comment]
Yes it does. even with the new shader you linked in the other thread.
The odd thing is this: another instance that was in the scene works fine when moved next to the red one but if i duplicate the red one it's still red.
![image](https://user-images.githubusercontent.com/26075468/101894491-18dafe80-3b5b-11eb-8f9c-933fd82a78de.png)
and the volume is global so it's not a trigger thing
![image](https://user-images.githubusercontent.com/26075468/101894626-4e7fe780-3b5b-11eb-8f7c-f26252245cd8.png)

**Comment by guycalledfrank** [comment]
Weird. Can you send me any package/project where I can reproduce it? I wonder if it's related to the volume data, or it's just not applied for some reason.

**Comment by laurentopia** [comment]
ok yeah
[bug red volume.zip](https://github.com/guycalledfrank/bakery-issues/files/5679080/bug.red.volume.zip)
that's what you should see when opened in a new project (2020.1.15 urp 8.20)
![image](https://user-images.githubusercontent.com/26075468/101903163-b557cd80-3b68-11eb-843c-a6b60112e2d3.png)

**Comment by guycalledfrank** [comment]
For some reason all script references are broken in your package:

![image](https://user-images.githubusercontent.com/7008423/101979888-13bca300-3c72-11eb-81ca-672f0440ec54.png)

I recreated the volume based on your screenshot and reproduced the problem though. The volume is looking weird indeed. There are different splotches of different color: 

![image](https://user-images.githubusercontent.com/7008423/101979935-70b85900-3c72-11eb-8c46-6e58c36d288a.png)

There are no lights in the scene so I can rebake it with different settings. Can you throw me a version of this scene with light objects and probably their (and the volume) scripts also present?

**Comment by laurentopia** [comment]
now it's black squares
![image](https://user-images.githubusercontent.com/26075468/102052124-87f26600-3d9a-11eb-8f23-ff0868627e05.png)
here is the scene, it should work, maybe i went far on the removing unnecessary script so might have no bakery stuff, still. but it might recognize the .meta file, so anyway if it doesn't, there is a mesh light on object "mr lava lava", and the main light has a bakery direct light and the volume is on volume, if you drop the script in debug mode i'll refill the values 
https://we.tl/t-EOWgLRVtvh

**Comment by laurentopia** [comment]
weird highlight in transition from lit to unlit
![image](https://user-images.githubusercontent.com/26075468/102053395-8b86ec80-3d9c-11eb-8163-68bb1e588400.png)
this is with your default spec volume shader

**Comment by laurentopia** [comment]
my guess is volume glitch happen with very bright mesh lights
![image](https://user-images.githubusercontent.com/26075468/102339052-7bf8d680-3f49-11eb-8f44-797dbeea1795.png)

i cranked the yellow sphere to 5 in intensity

**Comment by guycalledfrank** [comment]
5 is totally OK. Even my Sponza example has sun set to 10. 

Just baked your last scene. Seems like the issue is denoiser-related.

Without denoiser:

![image](https://user-images.githubusercontent.com/7008423/102342390-38828480-3faa-11eb-9562-9fd648f1d341.png)

With denoiser:

![image](https://user-images.githubusercontent.com/7008423/102342441-489a6400-3faa-11eb-8a86-c626afc6ab14.png)


I think denoiser doesn't work great for very low-resolition images, as it's hard to tell actual content from noise. And it looks like in your scene it still looks pretty good even with denoise off on the volume.

**Comment by laurentopia** [comment]
I kept denoise for the lightmap and turned off denoise in the colume component and the artifact is gone.
