### ISSUE TITLE
.uvgblog.txt isn't released so collab cannot write over

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#46]
after a bake the log still open by bakery

**Comment by guycalledfrank** [comment]
This file shouldn't be synced by collab or any other version control. In fact, I added the "." in the filename just to make Unity ignore it (it won't show up in the asset browser). I guess you can also add it to collab-specific ignore list: https://docs.unity3d.com/560/Documentation/Manual/UnityCollaborateIgnoreFiles.html

**Comment by laurentopia** [comment]
that's what I though, ok I'll add that file to the ignore. Thanks.
