### ISSUE TITLE
URP shaders undeclared identifiers : many errors in the console 

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#47]
![image](https://user-images.githubusercontent.com/26075468/101848366-20be8280-3b0a-11eb-8d17-26419ddbca79.png)

**Comment by guycalledfrank** [comment]
I know, but they should still work in the scene.
Also, added a guard against it yesterday (and also another graph): https://drive.google.com/file/d/14gKWpEl_adF0euOMHLbGBcF7Fqm310Jb/view?usp=sharing
