### ISSUE TITLE
Real Time Preview only updates when directly changing a Bakery Light component

### ISSUE THREAD

**Issue by Zurigan** [guycalledfrank/bakery-issues#48]
I have a simple 'lights manager' component with a bunch of bakery directional lights as children that I want to be able to update/preview all at once. Looks like this:

![image](https://user-images.githubusercontent.com/3914073/101934670-c4537580-3b92-11eb-84c8-e78a36aa1e0c.png)

Updating color or intensity doesn't get reflected in RTP even though the Bakery component values are getting updated. The only way to make this work is to hop in/out of preview which defeats the purpose of it. 

Discovered I could hack this to work by including `BakeryDirectLight.lightsChanged = 1;` in my manager every time I change a light ... would be good not to have to do that though.

For a cleaner setup maybe change Update() in Bakery Lights to check if values had updated?

**Comment by Zurigan** [comment]
You _could_ change Update() in Bakery Lights to look like this:

`private float lastKnownIntensity;
    void Update()
    {
        // ...
        if (lastKnownIntensity != intensity)
        {
            lightsChanged = 1;
            lastKnownIntensity = intensity;
        }    
    }
`

That way it'll just work as expected for any idiot like me in the future without having to dig through your code.

**Comment by guycalledfrank** [comment]
I could do that, but I didn't for performance reasons (lots of properties, potentially lots of lights, too much data to compare for not good reason). I don't think there is a major problem adding 1 line to force refresh the preview, added some docs: https://geom.io/bakery/wiki/index.php?title=RTPreview#Scripting

**Comment by Zurigan** [comment]
Thanks for adding that to the docs, sure it'll be helpful for someone, someday!

Out of curiosity ... is there a good reason for duplicating the code between all the Bakery Lights? I'd assumed they could/would all inherit from something like `BakeryLight.cs`.
