### ISSUE TITLE
Metal URP shader errors

### ISSUE THREAD

**Issue by fender** [guycalledfrank/bakery-issues#55]
When building for iOS there are some shader errors on URP:

<img width="673" alt="image" src="https://user-images.githubusercontent.com/1436470/102094254-080be080-3e1a-11eb-81c8-97e262eb17af.png">

**Comment by guycalledfrank** [comment]
Interesting. Looks like it's using TEXTURE2D_ARGS define from GLES2.hlsl when building to iOS instead of the correct file for some reason, can't explain it otherwise.

Added an explicit branch for metal, can you check with this file? https://drive.google.com/file/d/1zbie-7oizCgouoNpQ3AOGueYxPXuFZnc/view?usp=sharing

**Comment by fender** [comment]
@guycalledfrank I'm actually having trouble getting Unity to reproduce that error consistently. I try "reimporting" the shader folder with and without the changes to that file and there are no errors either way. Any tips?

**Comment by fender** [comment]
It does show the errors here but with old line numbers even after updating your file and reimporting the entire shaders folder and restarting Unity 
<img width="633" alt="image" src="https://user-images.githubusercontent.com/1436470/102713264-dfbf2e80-42be-11eb-90db-abee64ee6b0e.png">

**Comment by guycalledfrank** [comment]
Weird. Maybe some shaders are cached somewhere? You might try deleting Library folder contents, so Unity is forced to reimport assets.

**Comment by fender** [comment]
So pressing Save Asset in the shader editor seemed to be the only way to do get it to clear the cache. 🤷 
Errors are gone, thanks. 👍

**Comment by fender** [comment]
@guycalledfrank Note that I had to also add the same for `SHADER_API_VULKAN` for Linux builds to work.
