### ISSUE TITLE
optix 5.1 (legacy) doesn't work if I remove optix 7 and 6 .dll from the folder

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#57]
![image](https://user-images.githubusercontent.com/26075468/102169574-5e434880-3e47-11eb-90fb-00870d9d179f.png)
![image](https://user-images.githubusercontent.com/26075468/102169684-9054aa80-3e47-11eb-9433-c44185330dcf.png)

![image](https://user-images.githubusercontent.com/26075468/102169649-7ca94400-3e47-11eb-84cc-38c1c3ab37aa.png)

**Comment by guycalledfrank** [comment]
Hmm. What does it say in the bottom of .denoiserlog.txt? Did you also delete any cud*.dll files?

**Comment by laurentopia** [comment]
oh i nuked that file as it wouldn't collaborate.
i nuked also opendenoise

**Comment by guycalledfrank** [comment]
cuda/cudnn files are required for OptiX 5.1.
cudnn (the largest one) is not needed by other denoisers though.
