### ISSUE TITLE
Unity 2020.1 HDRP crash

### ISSUE THREAD

**Issue by Jason-Ma-233** [guycalledfrank/bakery-issues#58]
![Snipaste_2020-12-17_01-12-24](https://user-images.githubusercontent.com/39983625/102382601-942e2b80-4005-11eb-9f01-25fd8670a5bb.png)
![Snipaste_2020-12-17_01-12-57](https://user-images.githubusercontent.com/39983625/102382632-9c866680-4005-11eb-8dfe-869524405ea8.png)
![Snipaste_2020-12-17_01-13-18](https://user-images.githubusercontent.com/39983625/102382651-a0b28400-4005-11eb-8c8e-9601e3e1c8c0.png)

`{ "dependencies": {	  

    "com.unity.2d.sprite": "1.0.0",
	
    "com.unity.burst": "1.4.1",
	
    "com.unity.cinemachine": "2.6.3",
	
    "com.unity.collab-proxy": "1.3.9",
	
    "com.unity.collections": "0.5.1-preview.11",
	
    "com.unity.formats.fbx": "3.2.1-preview.2",
	
    "com.unity.ide.rider": "1.2.1",
	
    "com.unity.ide.visualstudio": "2.0.5",
	
    "com.unity.ide.vscode": "1.2.3",
	
    "com.unity.jobs": "0.7.0-preview.17",
	
    "com.unity.polybrush": "1.0.2",
	
    "com.unity.render-pipelines.high-definition": "8.3.1",
	
    "com.unity.render-pipelines.high-definition-config": "8.3.1",
	
    "com.unity.test-framework": "1.1.19",
	
    "com.unity.timeline": "1.4.5",
	
    "com.unity.ugui": "1.0.0",
	
    "com.unity.modules.ai": "1.0.0",
	
    "com.unity.modules.androidjni": "1.0.0",
	
    "com.unity.modules.animation": "1.0.0",
	
    "com.unity.modules.assetbundle": "1.0.0",
	
    "com.unity.modules.audio": "1.0.0",
	
    "com.unity.modules.cloth": "1.0.0",
	
    "com.unity.modules.director": "1.0.0",
	
    "com.unity.modules.imageconversion": "1.0.0",
	
    "com.unity.modules.imgui": "1.0.0",
	
    "com.unity.modules.jsonserialize": "1.0.0",
	
    "com.unity.modules.particlesystem": "1.0.0",
	
    "com.unity.modules.physics": "1.0.0",
	
    "com.unity.modules.physics2d": "1.0.0",
	
    "com.unity.modules.screencapture": "1.0.0",
	
    "com.unity.modules.terrain": "1.0.0",
	
    "com.unity.modules.terrainphysics": "1.0.0",
	
    "com.unity.modules.tilemap": "1.0.0",
	
    "com.unity.modules.ui": "1.0.0",
	
    "com.unity.modules.uielements": "1.0.0",
	
    "com.unity.modules.umbra": "1.0.0",
	
    "com.unity.modules.unityanalytics": "1.0.0",
	
    "com.unity.modules.unitywebrequest": "1.0.0",
	
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
	
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
	
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
	
    "com.unity.modules.unitywebrequestwww": "1.0.0",
	
    "com.unity.modules.vehicles": "1.0.0",
	
    "com.unity.modules.video": "1.0.0",
	
    "com.unity.modules.vr": "1.0.0",
	
    "com.unity.modules.wind": "1.0.0",
	
    "com.unity.modules.xr": "1.0.0"	
  } }`

**Comment by guycalledfrank** [comment]
Can you check if that happens if you set Atlas Packer to Default? https://geom.io/bakery/wiki/index.php?title=Manual#Atlas_Packer

**Comment by Jason-Ma-233** [comment]
I tried the default and xatlas respectively, and they both cause a crash

**Comment by guycalledfrank** [comment]
Can you send me your Editor.log right after the crash? It is usually located in C:\Users\YourName\AppData\Local\Unity\Editor\

**Comment by guycalledfrank** [comment]
Also just to confirm - is Unwrapper also set to default (NOT xatlas)?

**Comment by Jason-Ma-233** [comment]
https://mega.nz/file/F7hilQJB#YsaItPBGgH0sdgoeGvDxmc_Bc-G4EoS1G61DsiSWOwg

Reproduction steps: create a new Unity2020 HDRP project, import bakery, and render lightmaps in the default scene with default settings

**Comment by guycalledfrank** [comment]
Bakery was tested on Unity 2020.1.14 and HDRP 8.2.0 before the latest release and didn't crash.

Just tested with the fresh project / default scene, didn't crash.

I see what's the problem, you're on DX12. Bakery needs Editor to be running in DX11 mode (at least during bake, you can switch to DX12 later).

I guess my default HDRP project worked out of the box because I'm on Win7, and it defaults to DX11.

Added GAPI detection, won't crash anymore, but will show an error message explaining the cause/what to do:
 https://github.com/guycalledfrank/bakery-csharp/commit/dad2c5eda10a3bbaa630d7d4b72dd8742d4e0fbe

You can download github updated via this: https://geom.io/bakery/wiki/index.php?title=Github_access

**Comment by Jason-Ma-233** [comment]
That's true. Thank you
