### ISSUE TITLE
request: easy way to bake skydome and lights in light volumes to remove all realtime lighting

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#66]
Here is the scenario:
I use exclusively volume light because they're faster than PBR realtime in URP
This works fantastically well in static environment but as soon as I use timeline to create an intro everything breaks
The reason: only one light volume can be baked at once in a scene
So what I propose is this: bake skydome + lights in volumes
workflow:
select all lights and skydome object and light volume, press bake volume and voila only the skydome and lights are baked, no GI no objects

current workflow is clunky as it requires to split each shot away in its own scene to bake, so if i have 20 shots in a timeline then 20 scenes it is even if only the lighting changes

**Comment by guycalledfrank** [comment]
Do you mean baking lighting without any shadows, occlusion or diffuse bounces into the volume? I guess you can do this by not marking anything to "Contribute GI", except for some random quad somewhere (as mentioned here: https://github.com/guycalledfrank/bakery-issues/issues/67)

**Comment by laurentopia** [comment]
ok I'll do that.
