### ISSUE TITLE
how do you bake only volumes with no static objects, only bakery lights?

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#67]
I'm getting this:
![image](https://user-images.githubusercontent.com/26075468/103725528-a3acee80-4f8b-11eb-86a4-a255cf60537f.png)

**Comment by guycalledfrank** [comment]
Uhhm, there is no such option yet. I guess you can just create some throwaway quad mesh with scale in lightmap = 0, that'll work.
