### ISSUE TITLE
OnEnable instead of Awake for global volumes

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#68]
this way we can use global volumes in timeline without having to increase setup complexity

    public void OnEnable()
    {
        if (isGlobal)
        {
            globalVolume = this;
            SetGlobalParams();
        }
    }

**Comment by guycalledfrank** [comment]
I think there was _some_ reason why I decided to go with Awake, but I forgot it. Probably.

Anyway, I can't see it breaking anything, and it actually makes sense, so changed it: https://github.com/guycalledfrank/bakery-csharp/commit/071cc0aaa4ca7fd3def91813301896622b0a3030
