### ISSUE TITLE
baking results inconsistent in realtime preview and also in bake

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#71]
![image](https://user-images.githubusercontent.com/26075468/111039914-865e2b80-83e5-11eb-8320-1e70ec91e612.png)
this object is using that shader
![image](https://user-images.githubusercontent.com/26075468/111039888-56168d00-83e5-11eb-94ef-72852532eee4.png)
which should bake properly
since those objects are also using this shader
![image](https://user-images.githubusercontent.com/26075468/111039897-6890c680-83e5-11eb-9a00-fd2c9d08d1bc.png)

**Comment by laurentopia** [comment]
and if i add a plane with URP baked lit, it doesn't get baked in preview.
![image](https://user-images.githubusercontent.com/26075468/111040030-08e6eb00-83e6-11eb-9c2a-aede3cecd393.png)
and if i bake it i get this scramble
![image](https://user-images.githubusercontent.com/26075468/111040114-83176f80-83e6-11eb-91f6-76133bc43943.png)

**Comment by guycalledfrank** [comment]
URP Baked Lit shader seems to work for me (testing in 2020.2.7, URP 10.3.2):

![image](https://user-images.githubusercontent.com/7008423/111043690-e5a75480-8454-11eb-8bb0-33c6fcd1e96f.png)


So the shader is not the cause. No UVs or something?

**Comment by laurentopia** [comment]
The metallic strawberry clearly has UV so that's not the cause.
When I switch it to baked lit it still doesn't light up so shader isn't the issue. Maybe a setting?
Here is mine.
![image](https://user-images.githubusercontent.com/26075468/111059837-55194600-844d-11eb-9be1-48394a0e341c.png)
![image](https://user-images.githubusercontent.com/26075468/111059847-61050800-844d-11eb-8fac-12da3da6f8e3.png)

**Comment by guycalledfrank** [comment]
Not sure. Can you bake the strawberry in a separate scene? If it still doesn't bake (related to single mesh/material), then it should be easy to track down the problem.

**Comment by laurentopia** [comment]
isolated scene, one bakery direct light, real time preview:
![image](https://user-images.githubusercontent.com/26075468/111188631-7cb5fe80-8572-11eb-9e2d-728aa2a5abb4.png)

**Comment by guycalledfrank** [comment]
Can you send me a unitypackage with this model/material/maps to check?

**Comment by laurentopia** [comment]
here it is
[strawberry.zip](https://github.com/guycalledfrank/bakery-issues/files/6151217/strawberry.zip)

**Comment by guycalledfrank** [comment]
Hi. Your graph doesn't compile because it can't find MeshAnimatorSubGraph. I removed it to test. It also used some different version of BakeryDecodeLightmap.hlsl, as you were feeding occlusion parameter to it. Removed it as well. 
I also had to re-export the model to FBX on a different PC, because I don't have Maya here. Unity doesn't have a built-in Maya importer, it just looks for Maya on your machine and asks it to export to fbx...

After that (with stuff cut from the graph and model coming from fbx), I tested strawberry, and it... seems to work:

RTPreview:

![image](https://user-images.githubusercontent.com/7008423/111879018-cb232d00-89b8-11eb-8093-392d213acddc.png)

Here it is with Baked Lit:

![image](https://user-images.githubusercontent.com/7008423/111879825-12112280-89b9-11eb-9b49-fcfdb1ebf8b7.png)

And with your graph (baked with strawberry not being static to prevent voxel self-occlusion):

![image](https://user-images.githubusercontent.com/7008423/111879872-5a304500-89b9-11eb-8259-b7a3fa814763.png)

So not sure how to reproduce the bug above.

**Comment by laurentopia** [comment]
That was quite an ordeal I put you through. Thanks for bearing with me.
So you're recommending that I remove the occlusion? 
What data does preview use for render?
I tested things with a simple cube.
It turns black with the strawberrie's texture and material settings
then if I switch smoothness from metallic off and set metallic and smoothness to 0 it works
![image](https://user-images.githubusercontent.com/26075468/111891385-ef2e4080-89af-11eb-8664-7e5b59c7a8dd.png)
but here is where it gets fun: if set the material parameters back to original it now works!
![image](https://user-images.githubusercontent.com/26075468/111891408-3ae0ea00-89b0-11eb-927a-5da21fdea7f3.png)
With this stunt the strawberry still look borked like bad UV. might be UV that you got right in by doing a separate fbx pass and the unity+maya importer being super borked, lemme try that. nope.
Might be related, maybe not related but what I see is preview keeps stuff that's been changed.
![image](https://user-images.githubusercontent.com/26075468/111891569-5f899180-89b1-11eb-9882-fa7202b5fe0c.png)
here the foliage has disappeared after i changed the shader to what you have and then I brought that old shader back from git and it's still gone. Also these green things at the top were erroneously set to bake, I switched that off but they still show up in preview.
I use version ... no idea... maybe add the version number in the preview window like you did with bake.
![image](https://user-images.githubusercontent.com/26075468/111891680-daeb4300-89b1-11eb-8e78-bdcd272726a3.png)
or if it's easier, in the console.

**Comment by guycalledfrank** [comment]
Not sure if occlusion is the problem. But maybe it is.
Preview reflects "how lightmapper sees the world", i.e. GI will bounce from the same color; the color is from Meta Pass of every shader; in case of graphs it should come from what you put to albedo/emission outputs.

> if set the material parameters back to original it now works!
OK wow this is confusing :) I'm not sure why it can be this way. Unity forgets to reset something on the shader?

Preview version doesn't matter in this case, it didn't change that much. Scene exporting is on the lightmapper's C# side.

Here is some idea: 
- graph overrides albedo with 0 and emission is tinted with the lightmap/volume.
- these values are used in the lightmapper/preview.
- albedo is 0 as in the graph and lightmap/volume is unitialized, hence black/weird color?
- however, it "works on my machine". For some reason.

... but my bet it's related, in case you CAN'T reproduce it with Baked Lit or other built-in shaders. 

Possible resolution: I can make some switch to force Bakery extract albedo/emission for GI not from the Meta Pass (your graph), but directly via common texture names (_BaseMap, _BaseColorMap, _MainTex, etc). Very easy to do globally. Less easy to do per-material. Maybe you can add some specially-named property to the shader and I can scan for it?

**Comment by laurentopia** [comment]
> Maybe you can add some specially-named property to the shader and I can scan for it?

That would work very well.

**Comment by guycalledfrank** [comment]
OK, I added a little patch.

Now if your shader has a property named BAKERY_FORCE_NO_META, it will ignore the meta pass and use _MainTex/_BaseColorMap/_BaseMap instead. 

e.g.
BAKERY_FORCE_NO_META ("BAKERY_FORCE_NO_META", Float) = 0.0

Here is how it can look in a graph:

![image](https://user-images.githubusercontent.com/7008423/113475677-c9a93880-947f-11eb-8b92-e6b533557a7c.png)


Can you try it?

**Comment by laurentopia** [comment]
absolutely amazing, man, thank you so much!
![image](https://user-images.githubusercontent.com/26075468/113522371-c8960b00-9554-11eb-840d-18f1d769e2e2.png)
![image](https://user-images.githubusercontent.com/26075468/113522915-3c3a1700-9559-11eb-8a5a-a360e185aea3.png)
