### ISSUE TITLE
bug: bakery settings cannot be resized and loses scrollbar

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#72]
![image](https://user-images.githubusercontent.com/26075468/111059825-403cb280-844d-11eb-9541-7e4bd3f33fca.png)
there is another page of settings
this is captured on a 1440p monitor

**Comment by guycalledfrank** [comment]
Yeah, I know. You can still use the mouse wheel to scroll though :D
Anyway, fair enough. Fixed it: https://github.com/guycalledfrank/bakery-csharp/commit/9b93601089f716536a858e2f636e499c38a00eb4
