### ISSUE TITLE
baking reflection probes at runtime freezes

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#77]
![image](https://user-images.githubusercontent.com/26075468/113636309-2561f600-9627-11eb-9545-9327cf4bfbb8.png)
but never goes away on cancel or stop

**Comment by laurentopia** [comment]
then this never recovers
![image](https://user-images.githubusercontent.com/26075468/113636404-5510fe00-9627-11eb-9dea-f3eb526375a2.png)

**Comment by guycalledfrank** [comment]
Oh. OK, added a few lines to ignore all buttons during play mode: https://github.com/guycalledfrank/bakery-csharp/commit/ef0fe6fa9ace790958e632d1f2de6774305b8255
