### ISSUE TITLE
RT preview ignores ambient occlusion

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#78]
AO is tricky to dial because it's so subtle so you have to push the knob to 11 then pull back, dichotomy is time consuming with the baker so RT supporting that would be nice.

**Comment by laurentopia** [comment]
![image](https://user-images.githubusercontent.com/26075468/114263448-5da46400-999a-11eb-8691-40216983e552.png)
![image](https://user-images.githubusercontent.com/26075468/114263574-37cb8f00-999b-11eb-9242-d2910719efda.png)

**Comment by guycalledfrank** [comment]
Well... added:

![image](https://user-images.githubusercontent.com/7008423/114276063-b3761c00-9a2d-11eb-90e3-3d1185baa92b.png)

![image](https://user-images.githubusercontent.com/7008423/114276067-b709a300-9a2d-11eb-9c86-4a7f3cae4f6a.png)

https://github.com/guycalledfrank/bakery-compiled/commit/2eb34ecc7908d2547723f74626847f9218435bfe
https://github.com/guycalledfrank/bakery-rtpreview-csharp/commit/4075b4dd39a6707dcd70dcef0098e6935d6a4ff5
