### ISSUE TITLE
wrong volumes scale, sometimes

### ISSUE THREAD

**Issue by laurentopia** [guycalledfrank/bakery-issues#92]
here is a strange one:
the volumes are baked properly but the scale seems incorrectly perceived by the shader
this is the scene you can see that the rocks in the middle right are overbright yet some object far away respond to volume lighting
![image](https://user-images.githubusercontent.com/26075468/115302089-dfbd2700-a116-11eb-94e1-52c78be2394f.png)

this is the scene with all other objects hidden by layer except this one box, same camera angle
![image](https://user-images.githubusercontent.com/26075468/115301949-b9978700-a116-11eb-8d86-0efbac9213a6.png)
you can see that volume exists and corresponds to the geometry, it's just shrunk down
bakery volume component scale is 1,1,1
![image](https://user-images.githubusercontent.com/26075468/115302208-08ddb780-a117-11eb-96a5-a4c4d3cf5bf1.png)
the script itself wasn't modified
the white cube is lit by the bakery default urp volume, no spec
no hlsl has changed in the past month, i verified with git.blame
this happens after i rebake a scene and some times when i loadasync additive
in the case of this scene shown here there was rebake but no loadasync

**Comment by guycalledfrank** [comment]
Is there only a single large global volume?

**Comment by laurentopia** [comment]
yes

**Comment by guycalledfrank** [comment]
Is it stuck like that forever or returns to normal scale after scene reload? I'm not sure how to reproduce this

**Comment by laurentopia** [comment]
so i went back to earlier commits and it used to work so i pasted the entire bakery folder to the newest commit and now it works...
makes no sense
here is the delta
![image](https://user-images.githubusercontent.com/26075468/115357632-b1b90080-a171-11eb-850a-bb071b1b124b.png)
i stay up to date to your commits and the one that works was probably a week old

**Comment by guycalledfrank** [comment]
Weird. Lightmapper itself doesn't affect volume packing in any way. It could be the scripts or the denoiser, but this...

**Comment by laurentopia** [comment]
yeah it doesn't make sense, maybe i gitignored some other scripts, lemme check... nope 
¯\_(ツ)_/¯

**Comment by laurentopia** [comment]
(i closed it to not clog your issue list, if this happens again after update we know where to look)
